### PR TITLE
Completes Hito 7

### LINKED ISSUE #16: v7.0.0 [Hito del curso]
Add task runner to project, start coding.

Deliverables:

- [x] Modify agil.yaml to include "lenguaje" and "taskfile"
- [ ] Create interface of a basic class  that corresponds to one user story.
- [ ] Add classes to agil.yaml?

### PR DESCRIPTION
**Pull request by jmrr**
The issue with poetry scripts is that they require a module:function callable and with `uvicorn` we need to call `uvicorn` binary unless we use `uvicorn.run()` or something.

Because v7.0.0 requires a task runner, let's leave that functionality there.

To try it out download and install [`mask`](https://github.com/jakedeichert/mask) happy to use `make` if you prefer.

### CODE REVIEW

**Comment by crisconru** [comment]
@jmrr is everything completed in this milestones?

**Comment by crisconru** [comment]
@jmrr why are you  changed errors imports from relative to absolute?

**Comment by jmrr** [comment]
Yeah @crisconru it was giving me errors so I used the fully qualified module path.

**Comment by jmrr** [comment]
I don't think it meets all the requirements. I've added them in the issue so I'll complete them.

**Comment by crisconru** [comment]
@jmrr say me when you need my accepted point of view hehehe (I can laugh in english "hahaha" or in spanish "jajaja", this is one of my superpowers)

**Comment by jmrr** [comment]
I think we still need to add some code. I'm free since yesterday so I can work on it today :muscle:

**Comment by crisconru** [comment]
I'm full this evening (mother-in-law birthday) and tomorrow (I'm required in a meetup) so I can't dedicated time until Friday. If you could advance by yourself, I would appreciate it.
If you need a PR review to advance too, give me a little whistle ;-)

**Comment by jmrr** [comment]
image


Of course man... oh I miss the family...

**Pull request merged**
